{% set name = "pshmem" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4e/cc/362ba427c012655cf12660352a1b9e96c5d0d484a07729e1e90db1b89774/{{ name }}-{{ version }}.tar.gz
  sha256: 8e96df0c47d0e3381f649ccff20deb0d76bf0e66b7873282579fe0e05b0fb22b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - pshmem

about:
  home: https://github.com/tskisner/pshmem
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel shared memory and locking with MPI
  description: |
    This is a small package that implements parallel design patterns using MPI
    one-sided and shared memory constructs.
  doc_url: https://github.com/tskisner/pshmem/README.md
  dev_url: https://github.com/tskisner/pshmem

extra:
  recipe-maintainers:
    - tskisner
