{% set name = "pshmem" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/84/54/65bcfe0a58e205c73d2bc3962336530f058228365eeddc51490e1c58c1bc/{{ name }}-{{ version }}.tar.gz
  sha256: 72445b872f5a0d85ef5ac0dbfaedc4413f5a66aa97244b1823d4d81f19a9492e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - sysv_ipc

test:
  imports:
    - pshmem

about:
  home: https://github.com/tskisner/pshmem
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel shared memory and locking with MPI
  description: |
    This is a small package that implements parallel design patterns using MPI
    one-sided and shared memory constructs.
  doc_url: https://github.com/tskisner/pshmem/README.md
  dev_url: https://github.com/tskisner/pshmem

extra:
  recipe-maintainers:
    - tskisner
