{% set name = "pshmem" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/34/c6/bbe690ad4c48c80956fa7f8e5d27a9b1534cc0711695d95dcbb813ea7b77/{{ name }}-{{ version }}.tar.gz
  sha256: fe0b6250835c65be1459c69471296bf1a4a8ab510627b6a7e491e6122677ae05

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - python-build
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pshmem

about:
  home: https://github.com/tskisner/pshmem
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel shared memory and locking with MPI
  description: |
    This is a small package that implements parallel design patterns using MPI
    one-sided and shared memory constructs.
  doc_url: https://github.com/tskisner/pshmem/README.md
  dev_url: https://github.com/tskisner/pshmem

extra:
  recipe-maintainers:
    - tskisner
