{% set name = "pshmem" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb12ccb667c7b44666eb1ed38d0d9ed0584cf10ca605f5dc13a31a288ac62b4a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - pshmem

about:
  home: https://github.com/tskisner/pshmem
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel shared memory and locking with MPI
  description: |
    This is a small package that implements parallel design patterns using MPI
    one-sided and shared memory constructs.
  doc_url: https://github.com/tskisner/pshmem/README.md
  dev_url: https://github.com/tskisner/pshmem

extra:
  recipe-maintainers:
    - tskisner
