{% set name = "pshmem" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tskisner/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c1edaff24c22f2df810cf5713131caeabc564dc95cbcb331b5046c18d6071d9a

build:
  noarch: python
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - python-build
    - setuptools >=80
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pshmem

about:
  home: https://github.com/tskisner/pshmem
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel shared memory and locking with MPI
  description: |
    This is a small package that implements parallel design patterns using MPI
    one-sided and shared memory constructs.
  doc_url: https://github.com/tskisner/pshmem/README.md
  dev_url: https://github.com/tskisner/pshmem

extra:
  recipe-maintainers:
    - tskisner
